spring:
  application:
    name: jrx-cloud-websocket
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health