spring:
  profiles:
    active: dev
  application:
    name: jrx-cloud-gateway
  cloud:
    config:
      discovery:
        serviceId: jrx-cloud-config
        enabled: true
      name: api-gateway, resilience4j
      label: master
      profile: ${spring.profiles.active}
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-api
          uri: lb://jrx-cloud-user
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /${path} # 将 /user 前缀剔除

jrx:
  gateway:
    ignorePaths: /auth/jwt
    tokenHeader: Access-Token

---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health