server:
  port: 18100
spring:
  profiles:
    active: dev
  application:
    name: jrx-cloud-config

encrypt:
  key-store:
    location: classpath:config-server.jks
    password: jrmarcco
    alias: config-server-key
    secret: jrmarcco

---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JrMarcco/jrx-config-server-repo.git
          default-label: master
          search-paths: /*, common/*
          username: JrMarcco@gmail.com
          password: JrMarcco!0
          basedir: jrx-test-config/config-repo
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: jrmarcco
    password: util